#cloud-config

chpasswd:
  users: 
  - name: admin
    password: "{{ next_password | password_hash }}"
    type: hash
  expire: False
system_info:
  default_user:
    name: ubuntu
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
timezone: UTC
users:
  - name: dasaint
    passwd: "{{ next_password | password_hash }}"
    shell: /bin/bash
    lock_passwd: false
#    ssh_pwauth: True
#    chpasswd: { expire: False }
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL