#cloud-config

chpasswd:
  users: 
  - name: admin
    password: "{{ next_password | password_hash }}"
    type: hash
  expire: False
f5_bigip_next:
  admin_password: "{{ next_password }}"
  setup:
    ntp: ['0.pool.ntp.org']
    vlans:
      -
        name: internal-trunk
        selfip: "{{ next_trunk_internal_ip }}"
        interface: 1.1
        tag: 192
      -
        name: external-trunk
        selfip: "{{ next_trunk_external_ip }}"
        interface: 1.1
        tag: 20
  onboard:
    platform:
      hostname: "{{ next_hostname }}"
      platformType: ve
system_info:
  default_user:
    name: ubuntu
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
timezone: UTC
write_files:
  - path: /etc/mbip/conf/values.yaml
    encoding: base64
    content: Z2xvYmFsOgogIGRlZmF1bHRUYWdzOgogICAgYWNjZXNzOiB0cnVlCiAgICBkbnM6IGZhbHNlCiAgICBkbnNWRTogZmFsc2UKICAgIGVmd0FjbDogZmFsc2UKICAgIGVmd0NHbmF0OiBmYWxzZQogICAgZWZ3SXBpOiBmYWxzZQogICAgZWZ3SXBzOiBmYWxzZQogICAgbHRtOiB0cnVlCiAgICBzc2xvOiBmYWxzZQogICAgd2FmOiB0cnVlCgogIHRhZ3M6CiAgICBhY2Nlc3M6IHRydWUKICAgIGRuczogZmFsc2UKICAgIGRuc1ZFOiBmYWxzZQogICAgZWZ3QWNsOiBmYWxzZQogICAgZWZ3Q0duYXQ6IGZhbHNlCiAgICBlZndJcGk6IGZhbHNlCiAgICBlZndJcHM6IGZhbHNlCiAgICBsdG06IHRydWUKICAgIHNzbG86IGZhbHNlCiAgICB3YWY6IHRydWUKCnRhZ3M6CiAgYWNjZXNzOiB0cnVlCiAgZG5zOiBmYWxzZQogIGRuc1ZFOiBmYWxzZQogIGVmd0FjbDogZmFsc2UKICBlZndDR25hdDogZmFsc2UKICBlZndJcGk6IGZhbHNlCiAgZWZ3SXBzOiBmYWxzZQogIGx0bTogdHJ1ZQogIHNzbG86IGZhbHNlCiAgd2FmOiB0cnVlCg==