---

- name: Create F5 Vars Dyanmic Group to Destroy
  ansible.builtin.include_tasks: 
    file: destroy_dyn_group_f5_vms.yml
  with_items: "{{ f5_ova_builds }}"
  loop_control:
    loop_var: ova_builds_var
     