---

  - name: Wait for VMware tools to become available for Central Manager
    community.vmware.vmware_guest_tools_wait:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      folder: /{{ datacenter_name }}/vm
      name: "{{ cm_hostname }}"
    delegate_to: localhost
