---

- name: BIG-IP Next Automation Join Next Instance to CM
  hosts: next-cm
  connection: httpapi
  gather_facts: true
  vars:
    ansible_httpapi_username: "{{ ansible_user }}"
    ansible_httpapi_password: "{{ cm_password }}"
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: f5networks.next.cm

  roles:
    #- roles/General-Roles/pause_5_min
    - roles/F5-Roles/Next/cm_next_instance_join
