---
#This Code is for 16.1 and above as the build contains a fix for guest customization to work correctly.

#Deploy OVA
- hosts: next-cm
  connection: httpapi
  gather_facts: true
  vars:
    ansible_httpapi_username: "{{ ansible_user }}"
    ansible_httpapi_password: "{{ ansible_password }}"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_network_os: f5networks.next.cm
  roles:
    - roles/General-Roles/date_time
    - roles/F5-Roles/NEXT/cm_get_info
    - roles/General-Roles/date_time