---

#Deploy CM Instance
- hosts: vCenter
  connection: local
  gather_facts: true
  roles:
    - roles/General-Roles/date_time
    - roles/vSphere-Roles/vSphere/create_resource_pool
    - roles/vSphere-Roles/Next/cm_deploy_ova
    - roles/vSphere-Roles/Next/cm_take_snapshot
    - roles/vSphere-Roles/Next/cm_generate_cloud_init
    - roles/vSphere-Roles/Next/cm_apply_cloud_init
    - roles/vSphere-Roles/Next/cm_power_on_vm
    - roles/F5-Roles/Next/cm_wait_online
    - roles/F5-Roles/Next/cm_reset_admin_password
    - roles/F5-Roles/Next/cm_bootstrap
    - roles/General-Roles/date_time

#Deploy Next Instance
- hosts: vCenter
  connection: local
  gather_facts: true
  roles:
    - roles/General-Roles/date_time
    - roles/vSphere-Roles/vSphere/create_resource_pool
    - roles/vSphere-Roles/Next/next_deploy_ova
    - roles/vSphere-Roles/Next/next_take_snapshot
    - roles/vSphere-Roles/Next/next_generate_cloud_init
    - roles/vSphere-Roles/Next/next_apply_cloud_init
    - roles/vSphere-Roles/Next/next_power_on_vm
    - roles/General-Roles/date_time
