---
#This Code is for 16.1 and above as the build contains a fix for guest customization to work correctly.

#Deploy OVA
- hosts: vCenter
  connection: local
  gather_facts: true
  roles:
    - roles/General-Roles/date_time
   # - roles/F5-Roles/XC/xc_create_virtual_network
    # - roles/F5-Roles/XC/xc_create_network_interface
    - roles/F5-Roles/XC/xc_create_fleet
    # - roles/F5-Roles/XC/xc_apply_fleet
    - roles/General-Roles/date_time