---

- name: show templating results metadata
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.template', 'metadata.yaml') | to_yaml }}"



- name: show templating results userdata
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.template', 'userdata.yaml') | to_yaml }}"