---

- name: Read file and modify with ansible variables
  set_fact:
    metadata: "{{ lookup('file','metadata.yml', split_lines=False)}}"
    userdata: "{{ lookup('file','userdata.yml', split_lines=False) | from_yaml}}"

- debug:
    var: metadata

- debug:
    var: userdata

- name: re-encode metadata and userdata into base64
  set_fact:
    base64_metadata: "{{ metadata | to_nice_yaml | b64encode  }}"
    base64_userdata: "{{ userdata | to_nice_yaml | b64encode  }}"

- debug:
    var: base64_metadata

- debug:
    var: base64_userdata