---

# - name: Read the yaml 
#   ansible.builtin.slurp:
#     path: 'metadata.yaml'
#   register: r_myfile
- name: extract the data
  set_fact:
    r_myfile: "{{ lookup('template','metadata.yaml', split_lines=False) }}"

- debug:
    var: r_myfile


- name: extract the data
  set_fact:
    mydata: "{{ r_myfile | from_yaml }}"

- debug:
    var: mydata


# - name: show templating results metadata
#   ansible.builtin.debug:
#     var: "{{ lookup('template','metadata.yaml', split_lines=False) }}"

# - name: show templating results userdata
#   ansible.builtin.debug:
#     var: "{{ lookup('template','userdata.yaml', split_lines=False) }}"