---

# - name: Read the yaml 
#   ansible.builtin.slurp:
#     path: 'metadata.yaml'
#   register: r_myfile
- name: extract the data
  set_fact:
    metadata: "{{ lookup('template','metadata.yaml', split_lines=False) | from_yaml}}"
    userdata: "{{ lookup('template','userdata.yaml', split_lines=False) | from_yaml}}"


- debug:
    var: metadata

- debug:
    var: userdata


# - name: show templating results metadata
#   ansible.builtin.debug:
#     var: "{{ lookup('template','metadata.yaml', split_lines=False) }}"

# - name: show templating results userdata
#   ansible.builtin.debug:
#     var: "{{ lookup('template','userdata.yaml', split_lines=False) }}"