---

- name: Read file and modify with ansible variables
  set_fact:
    metadata: "{{ lookup('template','metadata.yaml', split_lines=False) | from_yaml}}"
    userdata: "{{ lookup('template','userdata.yaml', split_lines=False) | from_yaml}}"

- debug:
    var: metadata

- debug:
    var: userdata

- name: re-encode metadata and userdata into base64
  set_fact:
    base64_metadata: "{{ metadata | b64encode | from_yaml }}"
    base64_userdata: "{{ userdata | b64encode | from_yaml }}"

- debug:
    var: base64_metadata

- debug:
    var: base64_userdata