---

- name: show templating results metadata
  ansible.builtin.debug:
    var: "{{ lookup('template','metadata.yaml', split_lines=False) }}"
    



- name: show templating results userdata
  ansible.builtin.debug:
    var: "{{ lookup('ansible.builtin.template', 'userdata.yaml') | to_yaml }}"