instance-id: "{{ cm_hostname }}"
local-hostname: "{{ cm_hostname }}"
network:
  version: 2
  ethernets:
    ens192:
      addresses: ["{{ cm_mgmt_ip }}"]
      gateway4: "{{ cm_mgmt_gw_ip }}"
      dhcp6: false
      nameservers:
        addresses:
          - "{{ dns_name_servers }}"
        search:
          - "{{ dns_name_search }}"
      dhcp4: false
      optional: true
