#cloud-config

system_info:
  default_user:
    name: ubuntu
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
users:
  - name: dasaint
    passwd: "{{ cm_password | password_hash }}"
    shell: /bin/bash
    lock-passwd: false
    ssh_pwauth: True
    chpasswd: { expire: False }
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
timezone: UTC
chpasswd:
  users: 
  - name: admin
    password: "{{ cm_password | password_hash }}"
    type: hash
  expire: False
