#cloud-config
users:
  - name: dasaint
    passwd: "{{ cm_password | password_hash }}"
    shell: /bin/bash
    lock_passwd: false
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
write_files:
  - path: /home/admin/myinstall.sh
    permissions: '0755'
    owner: admin:admin
    content: |
      #!/bin/bash
      until [ -f /var/lib/f5/central-manager/node-setup-complete ]
      do
        sleep 5
      done
      echo "ready"
      /opt/cm-bundle/cm install
runcmd:
  - [sudo, -u, admin, /home/admin/myinstall.sh]
chpasswd:
  users: 
  - name: admin
    password: "{{ cm_password | password_hash }}"
    type: hash
  expire: False