#cloud-config

chpasswd:
  users: 
  - name: admin
    password: "{{ cm_password | password_hash }}"
    type: hash
  expire: False
system_info:
  default_user:
    name: ubuntu
    lock_passwd: false
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
timezone: UTC
users:
  - name: dasaint
    passwd: "{{ cm_password | password_hash }}"
    shell: /bin/bash
    lock-passwd: false
    ssh_pwauth: True
    chpasswd: { expire: False }
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL 
runcmd:
#  - [passwd, --expire, admin]
  - [sleep, 300]
  - [sudo, -u, admin, bash, -c, "cat /home/admin/setup.txt | setup"]
write_files:
  - path: /home/admin/setup.txt
    permissions: '0644'
    owner: admin:admin
    content: |
      "{{ cm_hostname }}"
      n
      "{{ ntp_servers[0] }}"
      "{{ ntp_servers[1] }}"
   
    
      n
      y
      y