---

#Deploy Next and CM Instance
- hosts: vCenter
  connection: local
  gather_facts: true
  roles:
    - roles/General-Roles/date_time
    - roles/vSphere-Roles/Next/cm_dyn_group_ova

- name: BIG-IP Next Automation Join Next Instance to CM
  hosts: next_cm_dynamic
  connection: httpapi
  gather_facts: true
  vars:
    ansible_user: "admin"
    ansible_httpapi_password: '{{ cm_password }}'
    ansible_httpapi_port: 443
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false
    ansible_network_os: f5networks.next.cm
    as3_tenant_name: "HTTP-Application-1"
    as3_tenant_name2: "HTTPS-Application-1"
  roles:
# Join Instance to CM
    - roles/F5-Roles/Next/cm_app_delivery_http
    - roles/F5-Roles/Next/cm_app_delivery_https
    - roles/General-Roles/date_time
