---

- name: Provision VM from Template 
  ansible.builtin.include_tasks: 
    file: clone_f5_vm.yml
  with_items: "{{ f5_ova_builds }}"
  loop_control:
    loop_var: ova_builds_var 

- name: Add Guest Customization (IP/GW/Passwords) 
  ansible.builtin.include_tasks: 
    file: guest_cust.yml
  with_items: "{{ f5_ova_builds }}"
  loop_control:
    loop_var: ova_builds_var

- name: Power ON VMs
  ansible.builtin.include_tasks: 
    file: power_on.yml
  with_items: "{{ f5_ova_builds }}"
  loop_control:
    loop_var: ova_builds_var
