---
# tasks insttall Declaritive Onboarding Latest

- name: Backup Next instance
  f5networks.next.cm_next_backup_restore:
    device_ip: "{{ hostvars[item].ansible_host }}"
    filename: "{{ hostvars[item].inventory_hostname }}{{ backup_filename }}"
    file_password: "{{ backup_filename_pass }}"
    state: backup
    timeout: 600
  loop: "{{ groups['next-instances'] }}"  #HARDCODED will change
  register: next_backup_output

- debug:
    var: next_backup_output
