---
# tasks insttall Declaritive Onboarding Latest

# - name: Change Communication
#   ansible.builtin.set_fact:
#     ansible_connection: httpapi

- debug:
    var: cm_user

- debug:
    var: cm_password

- name: Get ALL Info from NEXT CM
  f5networks.next.cm_device_info:
    gather_subset:
      - all
  register: next_output

- name: Debug Information from Next CM
  ansible.builtin.debug:
    var: next_output
