---

- name: Collect users and files information on CM device
  f5networks.next.cm_device_info:
    gather_subset:
      - all
  register: cm_info

# - name: Debug CM-Info
#   ansible.builtin.debug:
#     var: cm_info

- name: Import Certificate/Key to Next
  f5networks.next.cm_ssl_certificate_import:
    name: App2-Certificate
    cert: "{{ role_path }}/files/new-app-demo.crt"
    key: "{{ role_path }}/files/new-app-demo.key"
    type: PEM
    update_cert: true
    update_key: true

# - name: Debug Declaration
#   ansible.builtin.debug:
#     msg: "{{ lookup('template', 'https_declaration.j2', split_lines=False) }}"

- name: Declaration with Next - AS3
  f5networks.next.cm_next_as3_deploy:
    content: "{{ lookup('template', 'https_declaration.j2', split_lines=False) }}"
    target_ip: "{{ item.hostname }}"
  with_items: "{{ cm_info.managed_devices }}"