---
# tasks file for Create-VM

 - name: Provision VM from Template 
   ansible.builtin.include_tasks:
     file: deploy_xc_ova.yml
   with_items: "{{ xc_ova_builds }}"
   loop_control:
     loop_var: ova_builds_var

 - name: Add Guest Customization (IP/GW/Passwords) 
   ansible.builtin.include_tasks:
     file: guest_cust.yml
   with_items: "{{ xc_ova_builds }}"
   loop_control:
     loop_var: ova_builds_var

 - name: Power ON VMs
   ansible.builtin.include_tasks:
     file: power_on.yml
   with_items: "{{ xc_ova_builds }}"
   loop_control:
     loop_var: ova_builds_var

 - name: Wait on VM Tools
   ansible.builtin.include_tasks:
     file: vmware_tools_wait.yml
   with_items: "{{ xc_ova_builds }}"
   loop_control:
     loop_var: ova_builds_var