---

  - name: Wait for VMware tools to become available
    community.vmware.vmware_guest_tools_wait:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      folder: /{{ datacenter_name }}/vm
      name: "{{ ova_builds_var.tmpl_name }}-{{ item }}"
    delegate_to: localhost
    register: facts
    with_sequence: "start=0 count={{ ova_builds_var.build_count }}" # format=%.3d"
