---
# tasks insttall Declaritive Onboarding Latest

- name: Reset default password for admin user
  ansible.builtin.uri:
    url: https://{{ cm_mgmt_ip[:-3] }}/api/change-password
    method: POST
    headers:
      Content-Type: application/json
    body: |
      {
          "username": "admin",
          "temp_password": "admin",
          "new_password": "{{ cm_password }}",
          "confirm_password": "{{ cm_password }}"
      }
    body_format: json
    timeout: 60
    status_code: 200
    validate_certs: false
  until: json_response.status == 200
  retries: 50
  delay: 30
  register: json_response
