---
  - name: Destroy F5 Clones
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false
      name: "{{ ova_builds_var.tmpl_name }}"
      state: absent
    delegate_to: localhost
