---
  - name: Powering Off (Forced) F5 VMs (Clones)
    community.vmware.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false
      name: "{{ ova_builds_var.tmpl_name }}"
      state: poweredoff
      force: true
    delegate_to: localhost
    ignore_errors: true
