---

- name: Collect BIG-IP information
  f5networks.f5_modules.bigip_device_info:
    gather_subset:
      - client-ssl-profiles
    provider: "{{provider}}"
  register: ssl_info
  delegate_to: localhost

- debug: 
    var: ssl_info

- name: "Show members belonging to pool"
  debug: "msg={{ item }}"
  loop: "{{ ssl_info.client_ssl_profiles | json_query(query_string) }}"
  vars:
    query_string: "[?name=='clientssl-secure']"

- name: New SSL cert upload
  f5networks.f5_modules.bigip_ssl_certificate:
    provider: "{{ provider }}"
    name: "New_Cert"
    content: "{{ lookup('file', 'ssl/app-demo.crt') }}"

- name: New SSL key upload
  f5networks.f5_modules.bigip_ssl_key:
    provider: "{{ provider }}"
    name: "New_Cert"
    content: "{{ lookup('file', 'ssl/app-demo.key') }}"

- name: Create a client SSL profile with a cert/key/chain setting
  f5networks.f5_modules.bigip_profile_client_ssl:
    provider: "{{ provider }}"
    state: present
    name: "New_Cert_ClientSSL_profile"
    cert_key_chain:
      - cert: "New_Cert"
        key: "New_Cert"
    ciphers: "{{ item.ciphers[0] }}"
  loop: "{{ ssl_info.client_ssl_profiles | json_query(query_string) }}"
  vars:
    query_string: "[?name=='clientssl-secure']"
