---
# tasks file for ASM-Role

 - name: Backup F5 Configuration
   include: f5_backup_config.yaml
   tags: 
     - backup

 - name: Clone Backup F5 Configuration to NAS
   include: clone_ucs_to_nas.yaml
   tags: 
     - backup
