---
# tasks file for Destroy-VM

- name: Power Off Force VMs
  ansible.builtin.include_tasks: 
    file: poweroff_f5_vms.yml
  with_items: "{{ f5_ova_builds }}"
  loop_control:
    loop_var: ova_builds_var

- name: Destroy Provisioned VMs 
  ansible.builtin.include_tasks: 
    file: destroy_f5_vms.yml
  with_items: "{{ f5_ova_builds }}"
  loop_control:
    loop_var: ova_builds_var
