---

- name: Create a snapshot for Next VM
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    folder: /{{ datacenter_name }}/vm
    name: "{{ next_hostname }}"
    state: present
    snapshot_name: "Snap"
    description: "Snap"
    validate_certs: no
  delegate_to: localhost