---
# tasks insttall Declaritive Onboarding Latest

- name: Check if BIG-IP Next Central Manager instance is available (HTTPS responding 405 on /api/login)
  ansible.builtin.uri:
    url: https://{{ cm_mgmt_ip }}/api/login
    method: GET
    status_code: 400
    validate_certs: false
  until: json_response.status == 400
  retries: 50
  delay: 30
  register: json_response
